// designer/src/app/features/workflow-designer/components/palette/node-palette/node-palette.component.ts
import { Component, Output, EventEmitter, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faBolt,
  faGlobe,
  faCodeBranch,
  faCircle,
  faCode,
  faChevronLeft,
  faChevronRight,
} from '@fortawesome/free-solid-svg-icons';
import { NodeType } from '@core/models/workflow.types';

interface NodeTypeInfo {
  type: NodeType;
  icon: any;
  label: string;
  colorClass: string;
}

@Component({
  selector: 'app-node-palette',
  standalone: true,
  imports: [CommonModule, FontAwesomeModule],
  templateUrl: './node-palette.component.html',
  styleUrl: './node-palette.component.scss',
})
export class NodePaletteComponent {
  isCollapsed = signal(false);

  // Icons
  faBolt = faBolt;
  faGlobe = faGlobe;
  faCodeBranch = faCodeBranch;
  faCircle = faCircle;
  faCode = faCode;
  faChevronLeft = faChevronLeft;
  faChevronRight = faChevronRight;

  nodeTypes: NodeTypeInfo[] = [
    { type: 'TRIGGER', icon: faBolt, label: 'Trigger', colorClass: 'text-warning' },
    { type: 'HTTP_REQUEST', icon: faGlobe, label: 'HTTP Request', colorClass: 'text-primary' },
    { type: 'CONDITION', icon: faCodeBranch, label: 'Condition', colorClass: 'text-info' },
    { type: 'DO_NOTHING', icon: faCircle, label: 'Do Nothing', colorClass: 'text-secondary' },
    { type: 'CODE', icon: faCode, label: 'Code', colorClass: 'text-danger' },
  ];

  @Output() addNode = new EventEmitter<NodeType>();

  onAddNode(type: NodeType): void {
    this.addNode.emit(type);
  }

  toggleCollapse(): void {
    this.isCollapsed.update((value) => !value);
  }
}

@if (isCollapsed()) {
  <div class="palette-collapsed bg-white border-end d-flex flex-column align-items-center p-2">
    <button
      type="button"
      class="btn btn-sm btn-outline-secondary"
      (click)="toggleCollapse()"
      title="Expand Node Palette"
    >
      <fa-icon [icon]="faChevronRight"></fa-icon>
    </button>
  </div>
} @else {
  <div class="palette-expanded w-25 bg-white border-end d-flex flex-column">
    <div class="d-flex align-items-center justify-content-between p-2 border-bottom">
      <h6 class="mb-0 text-muted">Node Palette</h6>
      <button
        type="button"
        class="btn btn-sm btn-outline-secondary"
        (click)="toggleCollapse()"
        title="Collapse Node Palette"
      >
        <fa-icon [icon]="faChevronLeft"></fa-icon>
      </button>
    </div>

    <div class="flex-grow-1 overflow-auto p-2">
      <div class="d-flex flex-column gap-2">
        @for (nodeType of nodeTypes; track nodeType.type) {
          <button
            type="button"
            class="btn btn-outline-light text-start d-flex align-items-center gap-3 p-3 border rounded node-palette-item"
            (click)="onAddNode(nodeType.type)"
          >
            <fa-icon [icon]="nodeType.icon" [class]="nodeType.colorClass"></fa-icon>
            <span class="small text-dark fw-medium">{{ nodeType.label }}</span>
          </button>
        }
      </div>

      <div class="mt-3 p-2 bg-light rounded border" style="background-color: #eff6ff !important; border-color: #bfdbfe !important;">
        <p class="small mb-0" style="font-size: 0.75rem; color: #1e40af;">
          Click a node type to add it to the canvas at the center.
        </p>
      </div>
    </div>
  </div>
}

// react-app/src/src/components/palette/NodePalette.tsx
import React, { useState } from 'react';
import { Zap, Globe, GitBranch, Circle, Code, ChevronLeft, ChevronRight } from 'lucide-react';
import { NodeType } from '../../types/workflow.types';

interface NodePaletteProps {
  onAddNode: (type: NodeType) => void;
}

const nodeTypes: Array<{ type: NodeType; icon: React.ReactNode; label: string; color: string }> = [
  { type: 'TRIGGER', icon: <Zap className="w-5 h-5" />, label: 'Trigger', color: 'text-yellow-500' },
  { type: 'API', icon: <Globe className="w-5 h-5" />, label: 'API Call', color: 'text-blue-500' },
  { type: 'CONDITION', icon: <GitBranch className="w-5 h-5" />, label: 'Condition', color: 'text-purple-500' },
  { type: 'DO_NOTHING', icon: <Circle className="w-5 h-5" />, label: 'Do Nothing', color: 'text-gray-400' },
  { type: 'CODE', icon: <Code className="w-5 h-5" />, label: 'Code', color: 'text-orange-500' },
];

export function NodePalette({ onAddNode }: NodePaletteProps) {
  const [isCollapsed, setIsCollapsed] = useState(false);

  if (isCollapsed) {
    return (
      <div className="bg-gray-50 border-r border-gray-200 flex flex-col items-center p-2">
        <button
          onClick={() => setIsCollapsed(false)}
          className="p-2 hover:bg-gray-200 rounded transition-colors"
          title="Expand Node Palette"
        >
          <ChevronRight className="w-5 h-5 text-gray-600" />
        </button>
      </div>
    );
  }

  return (
    <div className="w-64 bg-gray-50 border-r border-gray-200 flex flex-col">
      <div className="flex items-center justify-between p-4 border-b border-gray-200">
        <h2 className="text-gray-700 font-medium">Node Palette</h2>
        <button
          onClick={() => setIsCollapsed(true)}
          className="p-1 hover:bg-gray-200 rounded transition-colors"
          title="Collapse Node Palette"
        >
          <ChevronLeft className="w-4 h-4 text-gray-600" />
        </button>
      </div>
      
      <div className="flex-1 overflow-y-auto p-4">
        <div className="space-y-2">
          {nodeTypes.map((nodeType) => (
            <button
              key={nodeType.type}
              onClick={() => onAddNode(nodeType.type)}
              className="w-full flex items-center gap-3 p-3 bg-white border border-gray-200 rounded-lg hover:border-blue-400 hover:shadow-sm transition-all cursor-pointer"
            >
              <div className={nodeType.color}>{nodeType.icon}</div>
              <div className="text-sm text-gray-700">{nodeType.label}</div>
            </button>
          ))}
        </div>
        
        <div className="mt-6 p-3 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-xs text-blue-800">
            Click a node type to add it to the canvas at the center.
          </p>
        </div>
      </div>
    </div>
  );
}
